"""Shared helpers for stage modules."""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from audit.config import FileCountConfig, HarnessConfig, StageConfig

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PROMPTS = REPO_ROOT / "prompts"
SCHEMAS = REPO_ROOT / "schemas"
RESULTS = REPO_ROOT / "results"
WORK = REPO_ROOT / "work"

# Default source-file extensions — used when config doesn't override.
# Covers all major languages.  Only files matching these extensions
# (plus _ALWAYS_COUNT_NAMES) are counted as "source files".
_DEFAULT_SOURCE_EXTENSIONS: tuple[str, ...] = (
    # JVM
    ".java", ".kt", ".kts", ".scala", ".groovy",
    # Python
    ".py", ".pyi", ".pyx",
    # JavaScript / TypeScript
    ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    # Go, Rust, Ruby, PHP, C#, Swift
    ".go", ".rs", ".rb", ".rake", ".php", ".phtml", ".cs", ".swift",
    # C / C++
    ".c", ".cpp", ".cc", ".cxx", ".c++", ".h", ".hpp", ".hh", ".hxx",
    # Shell
    ".sh", ".bash", ".zsh", ".fish",
    # Data / schema
    ".sql", ".proto", ".graphql",
    # Web
    ".html", ".htm", ".css", ".scss", ".less", ".sass", ".svelte", ".vue",
    # Config / markup / data
    ".yml", ".yaml", ".toml", ".cfg", ".ini", ".conf", ".xml", ".json",
    # Infra-as-code
    ".tf", ".tfvars", ".bzl", ".bazel",
    # Documentation (often contains security-relevant design notes)
    ".md", ".rst",
)

# Files always counted as source regardless of extension.  These are
# standard build / config entry-points found at the repo root (or in
# well-known subdirectories).
_ALWAYS_COUNT_NAMES: frozenset[str] = frozenset({
    "Makefile", "makefile", "GNUmakefile",
    "Dockerfile", "Dockerfile.prod", "Dockerfile.dev",
    "docker-compose.yml", "docker-compose.yaml",
    ".gitignore", ".dockerignore",
})

# Directories always excluded.
_COUNT_EXCLUDE_DIRS = frozenset({
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    "target", "build", "dist", "out", ".next", ".turbo", "coverage",
    ".pytest_cache", ".mypy_cache", ".tox", ".eggs", ".cache",
    "BOOT-INF", "META-INF", ".mvn", "gradle",
})

# OS metadata — never source code.
_COUNT_EXCLUDE_NAMES = frozenset({
    ".DS_Store", "Thumbs.db", "desktop.ini",
})

# Known audit-output basenames excluded when at the repo root.  These
# are generated by the pipeline itself — never project source.  Kept
# narrow to avoid false positives (e.g. "verdict_f_" not "verdict_").
_COUNT_EXCLUDE_ROOT_BASENAMES: tuple[str, ...] = (
    "report.json",
    "recon_output.json",
    "gapfill_output.json",
    "feedback_output.json",
    "trace_output.json",
    "trace_f",           # starts-with: trace_f_<finding_id>.json
    "verdict_f",         # starts-with: verdict_f_<finding_id>.json
)


def _effective_extensions(config: FileCountConfig | None) -> tuple[str, ...]:
    """Return the extension whitelist to use, falling back to defaults."""
    if config and config.source_extensions:
        return tuple(config.source_extensions)
    return _DEFAULT_SOURCE_EXTENSIONS


def count_source_files(
    repo_path: Path,
    config: FileCountConfig | None = None,
) -> int:
    """Count source-code files, using a configurable extension whitelist.

    Only files whose extension appears in the whitelist (or whose
    basename is in ``_ALWAYS_COUNT_NAMES``) are counted.  Directories
    like ``.git``, ``node_modules``, ``target/`` etc. are always
    skipped, as are OS metadata files (``.DS_Store``, …).

    Prefers ``git ls-files`` (respects .gitignore); falls back to a
    manual walk for non-git repos.
    """
    extensions = _effective_extensions(config)

    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), "ls-files",
             "--cached", "--others", "--exclude-standard"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            count = 0
            for line in result.stdout.splitlines():
                path = line.strip()
                if not path:
                    continue
                basename = path.rsplit("/", 1)[-1]
                if _is_source(basename, path, extensions):
                    count += 1
            return count
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass

    # Fallback: walk the tree.
    count = 0
    for entry in repo_path.rglob("*"):
        if not entry.is_file():
            continue
        parts = entry.relative_to(repo_path).parts
        if _COUNT_EXCLUDE_DIRS & set(parts):
            continue
        if not _is_source(entry.name, str(entry.relative_to(repo_path)), extensions):
            continue
        count += 1
    return count


def _is_source(basename: str, full_path: str, extensions: tuple[str, ...]) -> bool:
    """Return True if the file should be counted as a source file."""
    if basename in _COUNT_EXCLUDE_NAMES:
        return False
    # Audit-output files at the repo root.  Check before the extension
    # whitelist so patterns like "report.json" are excluded even though
    # .json is a recognised extension.
    if "/" not in full_path:
        for pat in _COUNT_EXCLUDE_ROOT_BASENAMES:
            if basename == pat or basename.startswith(pat):
                return False
    if basename in _ALWAYS_COUNT_NAMES:
        return True
    # Any extension in the whitelist.
    if basename.endswith(extensions):
        return True
    return False


@dataclass
class StageContext:
    run_id: str
    repo_path: Path
    config: HarnessConfig
    # Optional operator context — when set, downstream prompts use them.
    live_target: dict | None = None    # {"url": "...", "credentials": {...}}
    scope_notes: str | None = None     # verbatim text appended to user_input
    # Cached file count — set once by orchestrator, used for dynamic caps.
    file_count: int | None = field(default=None, repr=False)

    def stage(self, name: str) -> StageConfig:
        return self.config.get(name)

    def extras(self) -> dict:
        """Optional fields merged into every agent's user_input."""
        out: dict = {}
        if self.live_target:
            out["live_target"] = self.live_target
        if self.scope_notes:
            out["scope_notes"] = self.scope_notes
        return out

    def prompt(self, name: str) -> Path:
        path = PROMPTS / f"{name}.md"
        if not path.exists():
            raise FileNotFoundError(f"Missing prompt: {path}")
        return path

    def schema(self, name: str) -> Path:
        path = SCHEMAS / f"{name}.schema.json"
        if not path.exists():
            raise FileNotFoundError(f"Missing schema: {path}")
        return path

    def results_dir(self, stage: str) -> Path:
        d = RESULTS / self.run_id / stage
        d.mkdir(parents=True, exist_ok=True)
        return d

    def work_dir(self, stage: str, ref: str | None = None) -> Path:
        d = WORK / self.run_id / stage / (ref or "default")
        d.mkdir(parents=True, exist_ok=True)
        return d


def truncated_recon_summary(full: dict, subsystem_filter: str | None = None) -> dict:
    """Pass only the architecture facts downstream agents need."""
    out: dict = {
        "architecture": full.get("architecture", {}),
        "subsystems": full.get("subsystems", []),
    }
    if subsystem_filter is not None:
        match = next(
            (s for s in out["subsystems"] if s.get("name") == subsystem_filter
             or subsystem_filter.startswith(s.get("path", "##nope##"))),
            None,
        )
        out["subsystem_for_task"] = match
    return out
